### ISSUE TITLE
readme: swift script example - name for balance file

### ISSUE THREAD

**Issue by reez** [thunderbiscuit/bitcoindevkit-scripts#4]
Maybe use

`swift sh 1.balance.swift`

 instead of 

`swift sh balance.swift`

since `1.balance.swift` is the name of the file, just to match.

**Comment by reez** [comment]
(I can open up a PR w this change)

**Comment by thunderbiscuit** [comment]
Yeah that'd be great. Would you also mind taking a look at the script itself and letting me know if it feels idiomatic to you? Anything you'd write differently I'm open to merge. Mostly looking for simplicity and readability for those scripts, so let me know what you think.

**Comment by reez** [comment]
> Yeah that'd be great. Would you also mind taking a look at the script itself and letting me know if it feels idiomatic to you? Anything you'd write differently I'm open to merge. Mostly looking for simplicity and readability for those scripts, so let me know what you think.

Absolutely. I'll do a PR for the README, and then I'll follow up later with any updates to the current script, and also hopefully contribute later too to adding additional items to match [android](https://github.com/thunderbiscuit/bitcoindevkit-scripts/tree/master/kotlin)
